name: CI/CD Pipeline for Hand Gesture App

on:
  push:
    branches:
      - Production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v3

      - name:  Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name:  Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name:  Run Pytest
        run: pytest tests/

      - name:  Deploy to EC2 via SSH
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd hand-gesture-deploy
            git pull origin main
            docker compose down
            docker compose up --build -d
