name: CI/CD Pipeline for Hand Gesture App

on:
  push:
    branches:
      - Production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name:  Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Pytest
      run: pytest tests/

    - name:  Build Docker image
      run: docker build -t hand-gesture-app .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        debug: true
        script: |
          echo "SSH Connection successful"

          # Install git if not present
          if ! command -v git &> /dev/null; then
            echo "Git not found. Installing..."
            sudo yum install -y git
          fi

          # Stop and remove any existing containers/images
          docker stop hand-gesture-app || true
          docker rm hand-gesture-app || true
          docker rmi hand-gesture-app || true

          # Clone repo if not exists
          if [ ! -d ~/hand-gesture-repo ]; then
            git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git ~/hand-gesture-repo
          fi

          # Enter repo and pull latest changes
          cd ~/hand-gesture-repo
          git pull origin main

          # Build and run the Docker container
          docker build -t hand-gesture-app .
          docker run -d --name hand-gesture-app -p 8000:8000 hand-gesture-app


