name: CI/CD Pipeline for Hand Gesture App

on:
  push:
    branches:
      - Production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name:  Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Pytest
      run: pytest tests/

    - name: Clean up to free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo docker system prune -af


    - name:  Build Docker image
      run: docker build -t hand-gesture-app .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        debug: true
        script: |
          echo "SSH Connection successful"
          docker stop hand-gesture-app || true
          docker rm hand-gesture-app || true
          docker rmi hand-gesture-app || true
          cd ~/hand-gesture-repo || git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git ~/hand-gesture-repo
          cd ~/hand-gesture-repo
          git pull origin Production
          docker build -t hand-gesture-app .
          docker run -d --name hand-gesture-app -p 8000:8000 hand-gesture-app

